// svelte-lottery/src/pages/PrizeTake.svelte
<script setup lang="ts">
import Icon from '@iconify/svelte';
import { hasAnyPrizes, loadPrizes, takePrize } from "common/model";
import type { Prize } from "common/model";
import { generateCandidates } from "common/model/util";
import Animate from "../components/Animate.svelte";
import Row from "../components/Row.svelte";
import RedPacket from "../components/RedPacket.svelte";
import { navigateTo } from 'svelte-router-spa';

const ANI_TIME = 0.3;

let selected: Prize = null;
let prizes = loadPrizes();
let round = 1;
let candidates: Prize[][] = [];

function backToConfig() {
  window.playAppear();
  navigateTo('/config');
}

$: {
  if (!hasAnyPrizes()) {
    backToConfig();
  }
  candidates = generateCandidates(prizes);
}

const onTakePrize = () => {
  const p = selected;
  if (!p) {
    window.playError();
    return;
  }
  window.playAppear();
  takePrize(p);
  selected = null;
  round++;
  console.log(`You got ${p.name}`);
  prizes = loadPrizes();
};

$: active = selected === null;

const onOpen = (prize: Prize) => {
  window.playHooray();
  selected = prize;
};
</script>

<div>
  <!-- svelte-ignore a11y-click-events-have-key-events -->
  <div on:click={backToConfig} class="back">
    <Icon icon="mdi:arrow-back-circle" style="font-size:4vh;color:coral"/>
  </div>
  <!-- svelte-ignore a11y-click-events-have-key-events -->
  <div class="container" on:click={onTakePrize}>
    {#each candidates as c, i}
    <Row>
      {#each c as r, j}
      <Animate
        active={active}
        delay={(i * 3 + j) * ANI_TIME * 0.8}
      >
        <RedPacket
          active={active}
          round={round}
          prize={r}
          onOpen={onOpen}
        />
      </Animate>
      {/each}
    </Row>
    {/each}
  </div>
</div>

<style>
@import "common/css/PrizeTake.css";
</style>

// vue-lottery/src/views/PrizeTake.vue
<script setup lang="ts">
//会被自动注册
import { BIconArrowLeftCircle } from "bootstrap-icons-vue";
import { hasAnyPrizes, loadPrizes, Prize, takePrize } from "common/model";
import { computed, defineComponent, h, ref, unref, watchEffect } from "vue";
import { generateCandidates } from "common/model/util";
import Animate, { ANI_TIME } from "../components/Animate.vue";
import Row from "../components/Row.vue";
import RedPacket from "../components/RedPacket.vue";
import { useRouter } from "vue-router";

const Back = defineComponent({
  // components: {
  //     BIconArrowLeftCircle,
  // },
  methods: {
    onClick() {
      window.playAppear();
      this.$router.back();
    },
  },
  render() {
    return h(
      "div",
      {
        class: "back",
        onClick: this.onClick,
      },
      h(BIconArrowLeftCircle, { color: "#c3a26e", "font-size": "4vh" })
    );
  },
});

const selected = ref<Prize | null>(null);
const prizes = ref(loadPrizes());
const round = ref(1);
let candidates: Prize[][] = [];
const router = useRouter();
watchEffect(() => {
  console.log("effect prizes", unref(prizes));
  if (!hasAnyPrizes()) {
    return router.back();
  }
  candidates = generateCandidates(prizes.value);
});

const onTakePrize = () => {
  const p = unref(selected);
  if (!p) {
    window.playError();
    return;
  }
  window.playAppear();
  takePrize(p);
  selected.value = null;
  round.value++;
  console.log(`You got ${p.name}`);
};

const active = computed(() => unref(selected) === null);

const onOpen = (prize: Prize) => {
  selected.value = prize;
  window.playHooray();
};
</script>

<template>
  <div>
    <Back />
    <!--className do works!!-->
    <div className="container" @click="onTakePrize">
      <Row v-for="(c, i) of candidates" :key="i">
        <Animate
          v-for="(r, j) in c"
          :key="j"
          :active="active"
          :delay="(i * 3 + j) * ANI_TIME * 0.8"
        >
          <RedPacket
            :active="active"
            :round="round"
            :prize="r"
            :onOpen="onOpen"
          />
        </Animate>
      </Row>
    </div>
  </div>
</template>

<style>
@import "common/css/PrizeTake.css";
</style>
