// uniapp-lottery/src/views/PrizeConfig.vue
<script setup lang="ts">
import { PRIZE_CONFIG, NO_PRIZE, PRIZE_NAME, PRIZE_COUNT } from "common/model/Strings";
import { loadPrizes, totalPrizes, hasAnyPrizes, Prize } from "common/model";

import * as util from "common/model/util";
import Row from "../components/Row.vue";

import { ref } from "vue";

type updatePrizeFunc = (index: number, f: util.onUpdateState) => (e: any)=>void

const prizes = ref(loadPrizes());

const updateState = (newPrizes: Prize[]) => {
  prizes.value = [...newPrizes];
};

function handleStart() {
  if (hasAnyPrizes()) {
    window.playAppear();
    uni.navigateTo({
		url: 'PrizeTake'
    })
  } else {
    window.playError();
    window.alert(NO_PRIZE);
  }
}

function onInputChangeWrap(index: number, f: updatePrizeFunc) {
  return (event: any) => {
	  console.log(event)
    const value = event.detail.value;
    const e = {target: {value}}
	f(index, updateState)(e)
  };
}

</script>

<template>
  <view class="LotteryView">
    <h1 class="title">{{ PRIZE_CONFIG }}</h1>
    <table aria-hidden="true">
      <thead>
        <tr>
          <th scope="col">{{ PRIZE_NAME }}</th>
          <th scope="cols">{{ PRIZE_COUNT }}</th>
        </tr>
      </thead>
      <tbody>
        <tr class v-for="({ name, count }, i) in prizes" :key="i">
          <td>
            <input
              name="name"
              placeholder="配置名称"
              :value="name"
              v-on:input="onInputChangeWrap(i, util.handleNameChange)($event)"
            />
          </td>
          <td>
            <input
			  class="input"
              name="count"
              type="number"
			  maxlength="3"
              :value="count"
              @input="onInputChangeWrap(i, util.handleCountChange)($event)"
            />
          </td>
          <td>
            <view
              class="button"
              @click="util.handleRemove(i, updateState)()"
            >
			        <uni-icons type="close" color="red" size="40"></uni-icons>
            </view>
          </td>
        </tr>
      </tbody>
      <tfoot>
        <tr>
          <th scope="row">共计：</th>
          <td>{{ totalPrizes() }}</td>
        </tr>
      </tfoot>
    </table>
    <Row>
      <view class="button" @click="util.handleAdd(updateState)()">
		<uni-icons type="plus" color="#c3a26e" size="5vh"></uni-icons>
      </view>
      <view class="button" @click="handleStart">
        <uni-icons type="circle" color="green" size="5vh"></uni-icons>
        <uni-icons style="position: absolute; left:2vh;" type="right" color="green" size="3vh"></uni-icons>
      </view>
    </Row>
  </view>
  <footer>
    Powered by ml@uni-app
  </footer>
</template>

<style scoped>
@import "common/css/PrizeConfig.css";
.input {
	width: 4rem;
	text-align: end;
}
</style>

// taro-lottery/src/pages/PrizeConfig.tsx
import React from "react";
import { PRIZE_CONFIG, NO_PRIZE, PRIZE_NAME, PRIZE_COUNT } from "common/model/Strings";
import { loadPrizes, Prize, totalPrizes, hasAnyPrizes } from "common/model";
import { FiMinusCircle, FiPlayCircle, FiPlusCircle } from "react-icons/fi";
import Row from "../components/Row";

import * as util from "common/model/util";
import { View } from "@tarojs/components";

import "common/css/PrizeConfig.css";


export default class PrizeConfig extends React.Component< any, { prizes: Prize[] } > {
  constructor(props: any) {
    super(props);
    this.state = {
      prizes: loadPrizes(),
    };
  }

  updateState = (newState: Prize[]) => {
    this.setState({ prizes: newState });
  };

  handleStart = () => {
    if (hasAnyPrizes()) {
      window.playAppear();
      // Taro.navigateTo({
      //   url: "/take",
      // })
      window.location.href='/take'
    } else {
      window.playError();
      window.alert(NO_PRIZE);
    }
  };

  render() {
    return (
      <div className="LotteryView">
        <h1 className="title">{PRIZE_CONFIG}</h1>
        <table>
          <thead>
            <tr>
              <th>{PRIZE_NAME}</th>
              <th>{PRIZE_COUNT}</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {this.state.prizes.map(({ name, count }, index) => (
              <tr key={index}>
                <td>
                  <input
                    className="input"
                    name="name"
                    placeholder="配置名称"
                    value={name}
                    onChange={util.handleNameChange(index, this.updateState)}
                  />
                </td>
                <td>
                  <input
                    className="input"
                    name="count"
                    type="number"
                    max={99}
                    min={0}
                    value={count}
                    onChange={util.handleCountChange(index, this.updateState)}
                  />
                </td>
                <td>
                  <View
                    className="button"
                    onClick={util.handleRemove(index, this.updateState)}
                  >
                    <FiMinusCircle size="4vh" color="red" />
                  </View>
                </td>
              </tr>
            ))}
          </tbody>
          <tfoot>
            <tr>
              <th>共计：</th>
              <td>{totalPrizes()}</td>
            </tr>
          </tfoot>
        </table>
        <Row>
          <View className="button" onClick={util.handleAdd(this.updateState)}>
            <FiPlusCircle size="5vh" color="#c3a26e" />
          </View>
          <View className="button" onClick={this.handleStart}>
            <FiPlayCircle size="5vh" color="green" />
          </View>
        </Row>
        <footer>
          Powered by ml@Taro-React
        </footer>
      </div>
    );
  }
}
