// react-lottery/src/components/RedPacket.tsx
import "common/css/RedPacket.css";
import React, { useEffect, useState } from "react";
import cx from "classnames";
import { Prize } from "common/model";
import { OPEN } from "common/model/Strings";
interface IProps {
  active: boolean
  round: number;
  onOpen: (prize: Prize) => void;
  prize: Prize;
}

export default function RedPacket(props: IProps): React.ReactElement {
  const handleOpen = () => {
    setOpen(true);  
    window.playAppear();
    props.onOpen(props.prize);
  };
  const [open, setOpen] = useState(true);

  useEffect(() => {
    setOpen(false);
  }, [props.round]);

  return (
    <div className={cx("redpacket", { shake: open })}>
      <div className="prize">
        <span>{props.prize.name}</span>
      </div>
      <div className={cx("redpacket-lower", { open })} />
      <div className={cx("redpacket-upper", { open })}>
        <div
          className={cx("redpacket-button", { fade: open })}
          onClick={props.active ? handleOpen : undefined}
        >
          {OPEN}
        </div>
      </div>
    </div>
  );
}

// svelte-lottery/src/components/RedPacket.svelte
<script lang="ts">
import type { Prize } from "common/model";
import { OPEN } from "common/model/Strings";

export let prize: Prize;
export let round: number;
export let onOpen: (prize: Prize) => void;
export let active: boolean;

let open = false;

const handleOpen = () => {
  console.log("open prize", prize.name);
  open = true;
  window.playAppear();
  onOpen(prize);
};

let lastRound = round;

$: if(lastRound !== round) {
    console.log("round change: %d", round)
    lastRound = round;
    open = false;
}

</script>

<div class="redpacket" class:shake={open}>
  <div class="prize">
    <span>{ prize.name }</span>
  </div>
  <div class='redpacket-lower' class:open />
  <div class='redpacket-upper' class:open>
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <div
      class='redpacket-button' class:fade={open}
      on:click|stopPropagation={active ? handleOpen : undefined}
    >
      { OPEN }
    </div>
  </div>
</div>

<style>
@import "common/css/RedPacket.css";
</style>
