// react-lottery/src/components/RedPacket.tsx
import "common/css/RedPacket.css";
import React, { useEffect, useState } from "react";
import cx from "classnames";
import { Prize } from "common/model";
import { OPEN } from "common/model/Strings";
interface IProps {
  active: boolean
  round: number;
  onOpen: (prize: Prize) => void;
  prize: Prize;
}

export default function RedPacket(props: IProps): React.ReactElement {
  const handleOpen = () => {
    setOpen(true);  
    window.playAppear();
    props.onOpen(props.prize);
  };
  const [open, setOpen] = useState(true);

  useEffect(() => {
    setOpen(false);
  }, [props.round]);

  return (
    <div className={cx("redpacket", { shake: open })}>
      <div className="prize">
        <span>{props.prize.name}</span>
      </div>
      <div className={cx("redpacket-lower", { open })} />
      <div className={cx("redpacket-upper", { open })}>
        <div
          className={cx("redpacket-button", { fade: open })}
          onClick={props.active ? handleOpen : undefined}
        >
          {OPEN}
        </div>
      </div>
    </div>
  );
}

// uniapp-lottery/src/components/RedPacket.vue
<script setup lang="ts">
//compose api in setup(props, context)
import type { Prize } from "common/model";
import { OPEN } from "common/model/Strings";
import { ref, watch } from "vue";

interface IProps {
  active: boolean;
  round: number;
  onOpen: (prize: Prize) => void;
  prize: Prize;
}
//compiler macro.
const props = defineProps<IProps>();

const open = ref(false);

const handleOpen = () => {
  console.log("open prize", props.prize.name);
  window.playAppear();
  open.value = true;
  props.onOpen(props.prize);
};

watch(
  () => props.round,
  () => {
    open.value = false;
  }
);
</script>

<template>
  <view :class="['redpacket', { shake: open }]">
    <view class="prize">
      <text>{{ prize.name }}</text>
    </view>
    <view :class="['redpacket-lower', { open }]" />
    <view :class="['redpacket-upper', { open }]">
      <view
        :class="['redpacket-button', { fade: open }]"
        @click.stop="active ? handleOpen() : undefined"
      >
        {{ OPEN }}
      </view>
    </view>
  </view>
</template>

<style>
@import "common/css/RedPacket.css";
</style>
